import * as THREE from 'three';
import { Reflector } from './vendor/Reflector.js';
import { RoomEnvironment } from './vendor/RoomEnvironment.js';
import { createLiquidExperience, flowGLSL } from './liquid.js';
import { collection } from './collection.js';
import { createGalleryFlow } from './gallery-flow.js';
import { createButterflies } from './butterflies.js';
const $=s=>document.querySelector(s), reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const looks=collection.map(item=>[item.title,item.description]);
const grid=document.querySelector('.look-grid');grid.replaceChildren();
collection.forEach((item,i)=>{const card=document.createElement('button');card.className='look';card.dataset.look=String(i);card.dataset.category=String(item.category);card.setAttribute('aria-label',item.title+' 컬렉션 보기');const image=document.createElement('img');image.src=item.image;image.alt=item.title+' 패션 화보';image.decoding='async';const meta=document.createElement('span');meta.className='look-meta';const title=document.createElement('span');title.className='look-name';title.textContent=item.title;const label=document.createElement('small');label.textContent=String(i+1).padStart(2,'0')+' — '+item.label;meta.append(title,label);card.append(image,meta);grid.append(card)});
let entered=false,exploring=false,audioContext,audioGain,soundOn=false,holdTarget=0,holdValue=0,holdTimer,pressOrigin,transitioning=false;
function audio(enabled){try{if(enabled&&!audioContext){audioContext=new AudioContext();audioGain=audioContext.createGain();audioGain.gain.value=0;audioGain.connect(audioContext.destination);[130.81,196,261.63,329.63].forEach((freq,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=freq;g.gain.value=.018/(i+1);o.connect(g);g.connect(audioGain);o.start()})}if(audioContext){audioContext.resume();audioGain.gain.setTargetAtTime(enabled?1:0,audioContext.currentTime,.8)}soundOn=enabled;document.body.classList.toggle('sound-on',enabled);$('#sound').setAttribute('aria-pressed',String(enabled));$('#sound').setAttribute('aria-label',enabled?'사운드 끄기':'사운드 켜기')}catch{soundOn=false}}
function enter(withAudio){if(entered)return;entered=true;document.body.classList.add('entered');$('#entry').inert=true;audio(withAudio);$('#world').focus({preventScroll:true})}$('#enter').onclick=()=>enter(true);$('#enter-muted').onclick=()=>enter(false);$('#sound').onclick=()=>audio(!soundOn);
function explore(value){exploring=value;document.body.classList.toggle('exploring',value);$('#explore-world').setAttribute('aria-pressed',String(value))}$('#explore-world').onclick=()=>{if(location.hash&&location.hash!=='#index')location.hash='index';explore(!exploring)};
const menu=$('#menu');function closeMenu(){if(!menu.open)return;menu.classList.add('closing');setTimeout(()=>{menu.close();menu.classList.remove('closing')},reduced?0:420)}$('#menu-toggle').onclick=()=>{menu.showModal();$('#menu-toggle').setAttribute('aria-expanded','true')};menu.querySelector('.close').onclick=closeMenu;menu.addEventListener('cancel',e=>{e.preventDefault();closeMenu()});menu.addEventListener('close',()=>$('#menu-toggle').setAttribute('aria-expanded','false'));menu.querySelectorAll('a').forEach(a=>a.onclick=closeMenu);$('#menu-world').onclick=()=>{closeMenu();location.hash='index';explore(true)};
function route(){const page=location.hash.slice(1);const isPage=page==='projects'||page==='contact';$('#projects').hidden=page!=='projects';$('#contact').hidden=page!=='contact';$('#home').hidden=isPage;document.body.classList.toggle('page-open',isPage);document.body.dataset.page=isPage?page:'index';document.querySelectorAll('.menu-links a').forEach(a=>a.classList.toggle('active',a.hash===(isPage?'#'+page:'#index')));if(isPage)explore(false);document.title=isPage?`FORME Studio — ${page==='projects'?'Collections':'Contact'}`:'FORME Studio — Creating the unexpected'}
function changePage(){if(!entered||reduced){route();return}document.body.classList.add('page-transition');transitioning=true;setTimeout(()=>{route();document.querySelectorAll('.page').forEach(p=>p.scrollTop=0)},360);setTimeout(()=>{document.body.classList.remove('page-transition');transitioning=false},850)}window.addEventListener('hashchange',changePage);route();
const dialog=$('#look-dialog');let detail=0;function showLook(i){detail=i;$('#detail-image').src=collection[i].image;$('#detail-image').alt=looks[i][0];$('#detail-title').textContent=looks[i][0];$('#detail-text').textContent=looks[i][1];if(!dialog.open)dialog.showModal()}document.querySelectorAll('[data-look]').forEach(b=>b.onclick=()=>showLook(+b.dataset.look));dialog.querySelector('.close').onclick=()=>dialog.close();$('#detail-next').onclick=()=>showLook((detail+1)%collection.length);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
const world=$('#world');let pointer=new THREE.Vector2(),drag=new THREE.Vector2(),last=new THREE.Vector2(),holding=false;
const travelVelocity=new THREE.Vector2();let lastTravelTime=0;
const canNavigate=()=>entered&&!document.body.classList.contains("page-open")&&!menu.open&&!dialog.open;
function resetView(){drag.set(0,0);travelVelocity.set(0,0);pointer.set(0,0)}
const smoothPointer=new THREE.Vector2(),cursorPosition=new THREE.Vector2(innerWidth/2,innerHeight/2),mousePosition=cursorPosition.clone();let mouseSeen=false,overControl=false;
window.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;pointer.set(e.clientX/innerWidth-.5,e.clientY/innerHeight-.5);mousePosition.set(e.clientX,e.clientY);mouseSeen=true;overControl=!!e.target.closest('a,button,dialog,.page,#entry');const eyes=document.querySelector('.eyes g');if(eyes&&!entered)eyes.style.transform=`translate(${pointer.x*4}px,${pointer.y*4}px) rotate(${pointer.x*4}deg)`;document.body.classList.toggle('over-control',overControl)});
document.documentElement.addEventListener('pointerleave',()=>{mouseSeen=false;pointer.set(0,0)});
function animateCursor(){const k=reduced?1:.22;cursorPosition.lerp(mousePosition,k);smoothPointer.lerp(pointer,reduced?1:.045);const c=$('#cursor');c.style.left=cursorPosition.x+'px';c.style.top=cursorPosition.y+'px';c.style.opacity=entered&&mouseSeen&&!overControl?'1':'0';const hero=$('.hero-copy');hero.style.setProperty('--px',`${reduced?0:smoothPointer.x*9}px`);hero.style.setProperty('--py',`${reduced?0:smoothPointer.y*6}px`);requestAnimationFrame(animateCursor)}requestAnimationFrame(animateCursor);
world.addEventListener('pointerdown',e=>{if(!canNavigate()||e.button!==0)return;world.focus({preventScroll:true});travelVelocity.set(0,0);lastTravelTime=performance.now();holding=true;pressOrigin={x:e.clientX,y:e.clientY};last.set(e.clientX,e.clientY);world.setPointerCapture(e.pointerId);document.body.classList.add('dragging');holdTimer=setTimeout(()=>{holdTarget=1;document.body.classList.add('holding')},350)});
world.addEventListener('pointermove',e=>{pointer.set(e.clientX/innerWidth-.5,e.clientY/innerHeight-.5);if(holding){if(Math.hypot(e.clientX-pressOrigin.x,e.clientY-pressOrigin.y)>12){clearTimeout(holdTimer);holdTarget=0;document.body.classList.remove("holding")}const now=performance.now(),seconds=Math.max((now-lastTravelTime)/1000,.016);const dx=-(e.clientX-last.x)/innerWidth*5.8,dy=(e.clientY-last.y)/innerHeight*3.2;drag.x=THREE.MathUtils.clamp(drag.x+dx,-2.2,2.2);drag.y=THREE.MathUtils.clamp(drag.y+dy,-.8,1.6);travelVelocity.set(THREE.MathUtils.clamp(dx/seconds,-3.5,3.5),THREE.MathUtils.clamp(dy/seconds,-2,2));lastTravelTime=now;last.set(e.clientX,e.clientY)}const c=$('#cursor');c.style.left=e.clientX+'px';c.style.top=e.clientY+'px';c.style.opacity=entered?'1':'0'});
function release(){if(performance.now()-lastTravelTime>100)travelVelocity.set(0,0);holding=false;holdTarget=0;clearTimeout(holdTimer);document.body.classList.remove('dragging','holding')}world.addEventListener('pointerup',release);world.addEventListener('pointercancel',release);window.addEventListener('blur',release);world.addEventListener('pointerleave',()=>{$('#cursor').style.opacity=0;pointer.set(0,0);if(!holding)release()});
world.addEventListener('keydown',e=>{if(!canNavigate())return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();drag.x=THREE.MathUtils.clamp(drag.x+(e.key==='ArrowLeft'?-.3:e.key==='ArrowRight'?.3:0),-2.2,2.2);drag.y=THREE.MathUtils.clamp(drag.y+(e.key==='ArrowUp'?.22:e.key==='ArrowDown'?-.22:0),-.8,1.6)}if(e.code==='Space'&&!e.repeat){e.preventDefault();holdTarget=1;document.body.classList.add('holding')}if(e.key==='Home'){e.preventDefault();resetView()}if(e.key==='Escape'){release();resetView();explore(false)}});world.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();release()}});
world.addEventListener("dblclick",()=>{if(canNavigate())resetView()});
window.addEventListener("blur",()=>travelVelocity.set(0,0));
// Spring-like magnetic buttons and a rolling label, matching the reference's small reactions.
document.querySelectorAll('.pill,.outline-pill').forEach(el=>{const label=document.createElement('span');label.className='roll-label';while(el.firstChild)label.append(el.firstChild);el.append(label);el.addEventListener('pointermove',e=>{if(reduced||e.pointerType==='touch')return;const r=el.getBoundingClientRect();el.style.setProperty('--mx',`${(e.clientX-r.left-r.width/2)*.13}px`);el.style.setProperty('--my',`${(e.clientY-r.top-r.height/2)*.25}px`)});el.addEventListener('pointerleave',()=>{el.style.setProperty('--mx','0px');el.style.setProperty('--my','0px')})});
const filterBar=document.createElement('div');filterBar.className='filters';filterBar.setAttribute('aria-label','컬렉션 필터');['All','Structure','Contrast','Movement'].forEach((name,i)=>{const b=document.createElement('button');const count=i===0?collection.length:collection.filter(item=>item.category===i-1).length;b.textContent=name+' '+count;b.setAttribute('aria-pressed',String(i===0));b.onclick=()=>{filterBar.querySelectorAll('button').forEach(other=>other.setAttribute('aria-pressed',String(other===b)));document.querySelectorAll('.look').forEach(card=>{card.hidden=i!==0&&Number(card.dataset.category)!==i-1});$('#projects').scrollTo({top:0,behavior:'instant'})};filterBar.append(b)});$('.page-heading').append(filterBar);
createGalleryFlow({reduced});
try{
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.VSMShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.86;world.append(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#e8d7db');scene.fog=new THREE.FogExp2('#e6d7df',.011);scene.environmentIntensity=.28;
 const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,160);camera.position.set(4.4,3.5,15.8);
 const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;room.dispose();pmrem.dispose();
 scene.add(new THREE.HemisphereLight('#f6efff','#a29aab',.85));const sun=new THREE.DirectionalLight('#fff0df',2.8);sun.position.set(-3,10,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-18;sun.shadow.camera.right=18;sun.shadow.camera.top=15;sun.shadow.camera.bottom=-15;sun.shadow.normalBias=.025;sun.shadow.bias=-.0002;sun.shadow.radius=5;sun.shadow.blurSamples=8;scene.add(sun);
 // Fine plaster grain on real architectural geometry.
 const noiseCanvas=document.createElement('canvas');noiseCanvas.width=noiseCanvas.height=256;const ctx=noiseCanvas.getContext('2d'),pixels=ctx.createImageData(256,256);let seed=42;function random(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}for(let i=0;i<pixels.data.length;i+=4){const n=180+random()*65;pixels.data[i]=n;pixels.data[i+1]=n;pixels.data[i+2]=n;pixels.data[i+3]=255}ctx.putImageData(pixels,0,0);const grain=new THREE.CanvasTexture(noiseCanvas);grain.wrapS=grain.wrapT=THREE.RepeatWrapping;grain.repeat.set(3,3);
 const plaster=new THREE.MeshStandardMaterial({color:'#d6bfb5',roughness:.94,bumpMap:grain,bumpScale:.035});const lightPlaster=plaster.clone();lightPlaster.color.set('#e2cec3');
 function block(w,h,d,x,y,z,mat=plaster){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
 // Tall left arcade, with actual arched openings.
 function arch(cx,width=3.05){const radius=width/2,spring=5.7,top=10.5;const shape=new THREE.Shape();shape.moveTo(-radius,top);shape.lineTo(radius,top);shape.lineTo(radius,spring);shape.absarc(0,spring,radius,0,Math.PI,false);shape.lineTo(-radius,top);const g=new THREE.ExtrudeGeometry(shape,{depth:.65,bevelEnabled:false,curveSegments:48});const m=new THREE.Mesh(g,plaster);m.position.set(cx,0,.25);m.castShadow=true;m.receiveShadow=true;scene.add(m)}
 [-10.25,-6.55].forEach(x=>arch(x));[-12.1,-8.4,-4.7].forEach(x=>block(.65,10.5,.65,x,5.25,.575));
 // Two vertical apertures open to the pastel sky.
 block(4,12,.7,-2,6,-3.8);block(1.35,12,.7,2.7,6,-3.8);block(5.8,12,.7,8.3,6,-3.8);block(2.05,3.05,.7,1.025,1.525,-3.8);block(2.05,3.4,.7,1.025,10.3,-3.8);block(2.05,1.4,.7,4.4,.7,-3.8);block(2.05,1.5,.7,4.4,11.25,-3.8);
 block(15,12,.65,-19.8,6,.575);block(1.3,12,4.4,-4.1,6,-1.35);
 const sky=new THREE.Mesh(new THREE.SphereGeometry(110,32,24),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 vP; void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec3 vP; void main(){float h=normalize(vP).y; vec3 pink=vec3(.91,.76,.82);vec3 blue=vec3(.54,.64,.86);vec3 col=mix(pink,blue,smoothstep(-.03,.45,h));float cloud=sin(vP.x*.09+vP.z*.03)*sin(vP.y*.35+vP.x*.06);col=mix(col,vec3(.98,.91,.93),smoothstep(.12,.8,cloud)*.4);gl_FragColor=vec4(col,1.0);}'}));scene.add(sky);
 block(10.5,1.9,4.0,4.2,.95,-2.45,lightPlaster);
 for(let i=0;i<8;i++){const h=.22*(i+1);block(4.35,h,.57,-.85,h/2,3.0-i*.55,lightPlaster)}
 const pearl=new THREE.Mesh(new THREE.SphereGeometry(.97,80,56),new THREE.MeshPhysicalMaterial({color:'#fff9f1',metalness:.08,roughness:.25,iridescence:1,iridescenceIOR:1.34,iridescenceThicknessRange:[200,600],clearcoat:1,clearcoatRoughness:.08,envMapIntensity:1.65}));pearl.position.set(2.0,2.87,-1.75);pearl.castShadow=true;scene.add(pearl);
 function rock(x,z,s){const g=new THREE.SphereGeometry(s,72,48),p=g.attributes.position;for(let i=0;i<p.count;i++){const a=p.getX(i),b=p.getY(i),c=p.getZ(i);const f=1+.021*Math.sin(a*17+b*13)*Math.cos(c*15)+.014*Math.sin(b*32+c*19);p.setXYZ(i,a*f,b*f*.72,c*f)}g.computeVertexNormals();const mat=new THREE.MeshStandardMaterial({color:'#c6b9ad',roughness:1,bumpMap:grain,bumpScale:.16});const m=new THREE.Mesh(g,mat);m.position.set(x,.05,z);m.castShadow=true;m.receiveShadow=true;scene.add(m)}rock(4.3,3.1,1.25);rock(8,5.3,1.85);rock(-10,1.8,1.0);
 const hillMat=new THREE.MeshStandardMaterial({color:'#bca8bf',roughness:1});for(let i=0;i<10;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(4+random()*3,24,12),hillMat);m.scale.set(1,.22+random()*.12,.7);m.position.set(-30+i*5,-.25,-13-random()*9);scene.add(m)}
 // Real planar reflection, distorted to form animated ripples.
 const waterShader={uniforms:THREE.UniformsUtils.clone(Reflector.ReflectorShader.uniforms),vertexShader:Reflector.ReflectorShader.vertexShader,fragmentShader:Reflector.ReflectorShader.fragmentShader};waterShader.uniforms.time={value:0};waterShader.fragmentShader=waterShader.fragmentShader.replace('void main() {','uniform float time;\nvoid main() {').replace('vec4 base = texture2DProj( tDiffuse, vUv );',`vec4 uv = vUv;
 vec2 p = vUv.xy / vUv.w;
 float nearWave = .3 + .7 * (1.0 - p.y);
 uv.x += (sin(p.y * 115.0 + time * 1.1) * .0017 + sin(p.y * 241.0 - time*.65 + p.x*32.0) * .001) * uv.w * nearWave;
 uv.y += sin(p.x * 47.0 + p.y*76.0 + time*.8) * .0016 * uv.w;
 vec4 base = texture2DProj(tDiffuse, uv);
 base.rgb = mix(base.rgb, vec3(.59,.57,.64), .19);
 base.rgb += .014 * sin(p.y*310.0+p.x*16.0+time);`);
 const water=new Reflector(new THREE.PlaneGeometry(180,180),{textureWidth:Math.min(innerWidth*1.3,1600),textureHeight:Math.min(innerHeight*1.3,1200),color:0x96929f,clipBias:.003,shader:waterShader,multisample:2});water.rotation.x=-Math.PI/2;water.position.y=.045;scene.add(water);
 const updateButterflies=createButterflies(scene,{reduced,camera,renderer});
 const dots=new THREE.BufferGeometry(),positions=new Float32Array(65*3);for(let i=0;i<positions.length;i+=3){positions[i]=(random()-.5)*25;positions[i+1]=random()*11;positions[i+2]=(random()-.5)*17}dots.setAttribute('position',new THREE.BufferAttribute(positions,3));const particles=new THREE.Points(dots,new THREE.PointsMaterial({color:'#fff5e9',size:.027,transparent:true,opacity:.6,depthWrite:false}));scene.add(particles);
 // A light lens pass keeps the reference's soft, slightly prismatic response.
 const renderSize=new THREE.Vector2();renderer.getDrawingBufferSize(renderSize);const target=new THREE.WebGLRenderTarget(renderSize.x,renderSize.y,{samples:2,type:THREE.HalfFloatType});
 const liquid=createLiquidExperience({scene,camera,renderer,reduced,isActive:()=>entered,onLook:showLook});
 const lensScene=new THREE.Scene(),lensCamera=new THREE.OrthographicCamera(-1,1,1,-1,0,1);const lens=new THREE.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:{...liquid.uniforms,image:{value:target.texture},time:{value:0},hold:{value:0},dive:{value:0},mouse:{value:new THREE.Vector2(.5,.5)}},vertexShader:'varying vec2 vUv; void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:`uniform sampler2D image;uniform float time;uniform float hold;uniform float dive;uniform vec2 mouse;varying vec2 vUv;
 ${flowGLSL}
 void main(){vec2 p=vUv-.5;float r=length(p);vec3 flow=fluidField(vUv);vec2 uv=vUv+p*r*r*(.008+hold*.075)+flow.xy;
 float wave=sin(length(uv-mouse)*36.-time*2.)*hold*.0025;uv+=normalize(uv-mouse+vec2(.0001))*wave;
 float pool=1.-smoothstep(.1,.48,vUv.y);uv.x+=sin(vUv.y*68.+time*2.4)*dive*pool*.008;
 vec2 chroma=p*(.0012+hold*.011)*r+flow.xy*.18;
 vec3 c=vec3(texture2D(image,uv+chroma).r,texture2D(image,uv).g,texture2D(image,uv-chroma).b);
 c=mix(c,c*vec3(.88,1.05,1.09),flow.z*.16+dive*pool*.12);
 float grain=fract(sin(dot(vUv+mod(time,1.),vec2(12.9898,78.233)))*43758.5453);c+=(grain-.5)*.019;c*=1.-smoothstep(.22,.78,r)*.12;gl_FragColor=vec4(c,1.);
 #include <tonemapping_fragment>
 #include <colorspace_fragment>
 }`});lensScene.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2),lens));
 const aim=new THREE.Vector3(-.4,3.0,-.7),currentAim=aim.clone();let elapsed=0,prev=0;
 renderer.setAnimationLoop(ms=>{if(document.hidden)return;const dt=Math.min((ms-prev)/1000,.05);prev=ms;if(!reduced)elapsed+=dt;const mobile=innerWidth<650;holdValue+=(holdTarget-holdValue)*(1-Math.exp(-dt*3));const response=1-Math.exp(-dt*7);const parallax=reduced?0:1;if(!holding&&canNavigate()&&!reduced){drag.addScaledVector(travelVelocity,dt);drag.x=THREE.MathUtils.clamp(drag.x,-2.2,2.2);drag.y=THREE.MathUtils.clamp(drag.y,-.8,1.6);travelVelocity.multiplyScalar(Math.exp(-dt*7.5))}const active=canNavigate()?1:0;const lateral=drag.x*7.8+smoothPointer.x*(exploring?11:8)*parallax*active;const tx=(mobile?5.4:4.4)+lateral,ty=Math.max(1.1,3.5+drag.y*4-smoothPointer.y*3.8*parallax*active);camera.position.x+=(tx-camera.position.x)*response;camera.position.y+=(ty-camera.position.y)*response;const tz=(mobile?20:15.8)-Math.sin(drag.x*.65)*1.4-(reduced?0:holdValue*2.2);camera.position.z+=(tz-camera.position.z)*response;currentAim.lerp(new THREE.Vector3(aim.x+lateral*.88,aim.y+drag.y*2.9-smoothPointer.y*2.3*parallax*active,aim.z),response);camera.lookAt(currentAim);const flowState=liquid.update(dt,elapsed);lens.uniforms.dive.value=reduced?0:flowState.divePulse;water.material.uniforms.time.value=elapsed*(1+holdValue*.3);particles.rotation.y=elapsed*.007;updateButterflies(elapsed);pearl.position.y=2.87+(reduced?0:Math.sin(elapsed*.6)*.025);pearl.rotation.y=elapsed*.035+smoothPointer.x*.2;lens.uniforms.time.value=elapsed;lens.uniforms.hold.value=reduced?0:holdValue;lens.uniforms.mouse.value.set(smoothPointer.x+.5,.5-smoothPointer.y);renderer.setRenderTarget(target);renderer.render(scene,camera);liquid.renderText();renderer.setRenderTarget(null);renderer.render(lensScene,lensCamera)});
 window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.getDrawingBufferSize(renderSize);target.setSize(renderSize.x,renderSize.y)});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#world-hint').textContent='3D 화면을 다시 보려면 페이지를 새로고침하세요.';explore(true)});document.body.classList.add('ready');
}catch(error){console.error('3D scene unavailable',error);document.body.classList.add('ready');$('#loading').textContent='3D를 지원하는 브라우저에서 감상해 주세요.'}






// Same-page home links return to the beginning of the scroll story.
document.querySelectorAll('a[href="#index"]').forEach(a=>a.addEventListener('click',()=>{if(document.body.dataset.page==='index')window.scrollTo({top:0,behavior:reduced?'instant':'smooth'})}));
