export const collection = [
 ['Soft Structure','VOLUME & TAILORING','부드러운 볼륨과 단단한 테일러링. 움직임을 따라 새로운 실루엣을 발견합니다.'],
 ['In Between','CONTRAST & BALANCE','검정과 흰색, 비움과 채움 사이에서 균형을 탐구합니다.'],
 ['Free Form','SPACE & MOVEMENT','몸과 옷 사이의 공간에서 자유로운 움직임이 시작됩니다.'],
 ['After Hours','SCULPTURE & SHADOW','단정한 선과 입체적인 형태가 만나는 저녁의 실루엣.'],
 ['Quiet Gesture','LIGHT & CONTRAST','빛과 그림자를 따라 드러나는 섬세한 표정.'],
 ['Unfold','MOTION & TEXTURE','움직임에 따라 펼쳐지는 새로운 비례와 질감.'],
 ['Second Skin','FORM & STRUCTURE','몸의 선을 따라 자연스럽게 이어지는 형태.'],
 ['Soft Focus','TONE & CONTRAST','낮은 채도와 부드러운 빛이 만드는 여백.'],
 ['Passing Light','RHYTHM & MOTION','스쳐 가는 빛과 움직임 속에 남는 순간.'],
 ['New Perspective','SHAPE & VOLUME','다른 시선에서 다시 발견하는 익숙한 실루엣.'],
 ['Chromatic Dream','COLOR & PLAY','과감한 컬러와 유쾌한 볼륨으로 펼쳐지는 새로운 상상.'],
 ['Golden Hour','DRAPE & COLOR','노란빛 드레이프와 선명한 포인트의 조화.'],
 ['Red Current','CONTRAST & ENERGY','강렬한 레드와 밝은 배경이 만들어내는 리듬.'],
 ['Citrus Muse','COUTURE & EXPRESSION','대담한 색 조합으로 완성한 조형적인 스타일.'],
 ['City Pop','STREET & COLOR','도시의 자유로운 움직임을 담은 컬러 룩.'],
 ['Scarlet Bloom','ELEGANCE & LIGHT','빛 속에서 피어나는 선명한 실루엣.'],
 ['Pink Statement','DETAIL & VOLUME','핑크 포인트와 독창적인 디테일의 만남.'],
 ['Prismatic Form','PATTERN & RHYTHM','다채로운 패턴으로 표현하는 유연한 개성.'],
 ['Coastal Color','SUMMER & MOVEMENT','바닷가의 빛과 자유로운 여름의 색채.'],
 ['Electric Blue','STRUCTURE & COLOR','선명한 블루와 자신감 있는 형태.'],
].map(([title,label,description],i)=>({title,label,description,category:i%3,image:`assets/look-${String(i+1).padStart(2,'0')}.jpg`}));
